export const featuredCars = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2023,
    price: 28999,
    images: ["/1.png"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 15000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 26499,
    images: ["/2.webp"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 12000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 3,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 42999,
    images: ["/3.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "Sedan",
    mileage: 8000,
    color: "Red",
    wishlisted: false,
  },
  {
    id: 4,
    make: "Ford",
    model: "F-150",
    year: 2021,
    price: 35990,
    images: ["/4.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Truck",
    mileage: 22000,
    color: "Gray",
    wishlisted: false,
  },
  {
    id: 5,
    make: "BMW",
    model: "X5",
    year: 2023,
    price: 58990,
    images: ["/5.jpg"],
    transmission: "Automatic",
    fuelType: "Hybrid",
    bodyType: "SUV",
    mileage: 9000,
    color: "White",
    wishlisted: true,
  },
  {
    id: 6,
    make: "Chevrolet",
    model: "Corvette",
    year: 2024,
    price: 74999,
    images: ["/6.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Coupe",
    mileage: 3000,
    color: "Yellow",
    wishlisted: false,
  },
];

export const carMakes = [
  { id: 1, name: "Hyundai", image: "/make/hyundai.webp" },
  { id: 2, name: "Honda", image: "/make/honda.webp" },
  { id: 3, name: "BMW", image: "/make/bmw.webp" },
  { id: 4, name: "Tata", image: "/make/tata.webp" },
  { id: 5, name: "Mahindra", image: "/make/mahindra.webp" },
  { id: 6, name: "Ford", image: "/make/ford.webp" },
  { id: 7, name: "Tesla", image: "/make/tesla.webp" },
  { id: 8, name: "Audi", image: "/make/audi.webp" },
  { id: 9, name: "Skoda", image: "/make/skoda.webp" },
  { id: 10, name: "Volkswagen", image: "/make/volkswagen.webp" },
  { id: 10, name: "Chevrolet", image: "/make/chevrolet.webp" },
];

export const bodyTypes = [
  { id: 1, name: "SUV", image: "/body/suv.webp" },
  { id: 2, name: "Sedan", image: "/body/sedan.webp" },
  { id: 3, name: "Hatchback", image: "/body/hatchback.webp" },
  { id: 4, name: "Convertible", image: "/body/convertible.webp" },
  { id: 5, name: "Coupe", image: "/body/coupe.webp" },
  { id: 6, name: "Truck", image: "/body/truck.webp" },
];

export const faqItems = [
  {
    question: "Como funciona o agendamento de test drive?",
    answer:
      "Basta encontrar um carro do seu interesse, clicar no botão 'Test Drive' e selecionar um horário disponível. Nosso sistema confirmará sua reserva e fornecerá todos os detalhes necessários.",
  },
  {
    question: "Posso buscar carros usando uma imagem?",
    answer:
      "Sim! Nossa busca por imagem com tecnologia de IA permite que você envie uma foto de um carro que gosta, e encontraremos modelos semelhantes em nosso estoque.",
  },
  {
    question: "Todos os carros são certificados e verificados?",
    answer:
      "Todos os carros listados em nosso site passam por um processo de verificação. Trabalhamos apenas com veículos cuja procedência é atrestada e verificada.",
  },
  {
    question: "O que acontece após eu agendar um test drive?",
    answer:
      "Após o agendamento, você receberá um e-mail de confirmação com todos os detalhes. Também entraremos em contato para confirmar e fornecer informações adicionais, se necessário.",
  },
];
