export const featuredCars = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2023,
    price: 28999,
    images: ["/1.png"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 15000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 26499,
    images: ["/2.webp"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 12000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 3,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 42999,
    images: ["/3.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "Sedan",
    mileage: 8000,
    color: "Red",
    wishlisted: false,
  },
  {
    id: 4,
    make: "Ford",
    model: "F-150",
    year: 2021,
    price: 35990,
    images: ["/4.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Truck",
    mileage: 22000,
    color: "Gray",
    wishlisted: false,
  },
  {
    id: 5,
    make: "BMW",
    model: "X5",
    year: 2023,
    price: 58990,
    images: ["/5.jpg"],
    transmission: "Automatic",
    fuelType: "Hybrid",
    bodyType: "SUV",
    mileage: 9000,
    color: "White",
    wishlisted: true,
  },
  {
    id: 6,
    make: "Chevrolet",
    model: "Corvette",
    year: 2024,
    price: 74999,
    images: ["/6.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Coupe",
    mileage: 3000,
    color: "Yellow",
    wishlisted: false,
  },
];

export const carMakes = [
  { id: 1, name: "Hyundai", image: "/make/hyundai.webp" },
  { id: 2, name: "Honda", image: "/make/honda.webp" },
  { id: 3, name: "BMW", image: "/make/bmw.webp" },
  { id: 4, name: "Tata", image: "/make/tata.webp" },
  { id: 5, name: "Mahindra", image: "/make/mahindra.webp" },
  { id: 6, name: "Ford", image: "/make/ford.webp" },
  { id: 7, name: "Tesla", image: "/make/tesla.webp" },
  { id: 8, name: "Audi", image: "/make/audi.webp" },
  { id: 9, name: "Skoda", image: "/make/skoda.webp" },
  { id: 10, name: "Volkswagen", image: "/make/volkswagen.webp" },
  { id: 10, name: "Chevrolet", image: "/make/chevrolet.webp" },
];

export const bodyTypes = [
  { id: 1, name: "SUV", image: "/body/suv.webp" },
  { id: 2, name: "Sedan", image: "/body/sedan.webp" },
  { id: 3, name: "Hatchback", image: "/body/hatchback.webp" },
  { id: 4, name: "Convertible", image: "/body/convertible.webp" },
  { id: 5, name: "Coupe", image: "/body/coupe.webp" },
  { id: 6, name: "Truck", image: "/body/truck.webp" },
];

export const faqItems = [
  {
    question: "Como funciona o agendamento de test drive?",
    answer:
      "Basta encontrar um carro do seu interesse, clicar no botão 'Test Drive' e selecionar um horário disponível. Nosso sistema confirmará sua reserva e fornecerá todos os detalhes necessários.",
  },
  {
    question: "Posso buscar carros usando uma imagem?",
    answer:
      "Sim! Nossa busca por imagem com tecnologia de IA permite que você envie uma foto de um carro que gosta, e encontraremos modelos semelhantes em nosso estoque.",
  },
  {
    question: "Todos os carros são certificados e verificados?",
    answer:
      "Todos os carros listados em nosso site passam por um processo de verificação. Trabalhamos apenas com veículos cuja procedência é atrestada e verificada.",
  },
  {
    question: "O que acontece após eu agendar um test drive?",
    answer:
      "Após o agendamento, você receberá um e-mail de confirmação com todos os detalhes. Também entraremos em contato para confirmar e fornecer informações adicionais, se necessário.",
  },
];

// export const tableData = [
//   {
//     id: "m5gr84i9",
//     amount: 316,
//     status: "success",
//     email: "ken99@example.com",
//   },
//   {
//     id: "3u1reuv4",
//     amount: 242,
//     status: "success",
//     email: "Abe45@example.com",
//   },
//   {
//     id: "derv1ws0",
//     amount: 837,
//     status: "processing",
//     email: "Monserrat44@example.com",
//   },
//   {
//     id: "5kma53ae",
//     amount: 874,
//     status: "success",
//     email: "Silas22@example.com",
//   },
//   {
//     id: "bhqecj4p",
//     amount: 721,
//     status: "failed",
//     email: "carmella@example.com",
//   },
//   {
//     id: "m5gr84i9",
//     amount: 316,
//     status: "success",
//     email: "ken99@example.com",
//   },
//   {
//     id: "3u1reuv4",
//     amount: 242,
//     status: "success",
//     email: "Abe45@example.com",
//   },
//   {
//     id: "derv1ws0",
//     amount: 837,
//     status: "processing",
//     email: "Monserrat44@example.com",
//   },
//   {
//     id: "5kma53ae",
//     amount: 874,
//     status: "success",
//     email: "Silas22@example.com",
//   },
//   {
//     id: "bhqecj4p",
//     amount: 721,
//     status: "failed",
//     email: "carmella@example.com",
//   },
//   {
//     id: "m5gr84i9",
//     amount: 316,
//     status: "success",
//     email: "ken99@example.com",
//   },
//   {
//     id: "3u1reuv4",
//     amount: 242,
//     status: "success",
//     email: "Abe45@example.com",
//   },
//   {
//     id: "derv1ws0",
//     amount: 837,
//     status: "processing",
//     email: "Monserrat44@example.com",
//   },
//   {
//     id: "5kma53ae",
//     amount: 874,
//     status: "success",
//     email: "Silas22@example.com",
//   },
//   {
//     id: "bhqecj4p",
//     amount: 721,
//     status: "failed",
//     email: "carmella@example.com",
//   },
//   {
//     id: "m5gr84i9",
//     amount: 316,
//     status: "success",
//     email: "ken99@example.com",
//   },
//   {
//     id: "3u1reuv4",
//     amount: 242,
//     status: "success",
//     email: "Abe45@example.com",
//   },
//   {
//     id: "derv1ws0",
//     amount: 837,
//     status: "processing",
//     email: "Monserrat44@example.com",
//   },
//   {
//     id: "5kma53ae",
//     amount: 874,
//     status: "success",
//     email: "Silas22@example.com",
//   },
//   {
//     id: "bhqecj4p",
//     amount: 721,
//     status: "failed",
//     email: "carmella@example.com",
//   },
// ];

// mocks/vehicle-mock-data.js
export const tableData = [
  // {
  //   id: "1",
  //   vehicleType: "SUV",
  //   vehicleBrand: "Toyota",
  //   model: "RAV4",
  //   year: 2021,
  //   price: 145000,
  //   color: "Branco",
  //   engineSize: "2.5L",
  //   mileage: 25000,
  //   fuelType: "Gasolina",
  //   transmission: "Automático",
  //   status: "Disponível",
  //   images: [
  //     "https://images.unsplash.com/photo-1622210642960-0f6a2cdbdc9f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "2",
  //   vehicleType: "Sedan",
  //   vehicleBrand: "Honda",
  //   model: "Civic",
  //   year: 2019,
  //   price: 95000,
  //   color: "Preto",
  //   engineSize: "2.0L",
  //   mileage: 50000,
  //   fuelType: "Flex",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: [
  //     "https://images.unsplash.com/160x120/?car,https://images.unsplash.com/photo-1661501315656-30e4496eeaad?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "3",
  //   vehicleType: "Hatch",
  //   vehicleBrand: "Volkswagen",
  //   model: "Golf",
  //   year: 2020,
  //   price: 105000,
  //   color: "Cinza",
  //   engineSize: "1.4L",
  //   mileage: 32000,
  //   fuelType: "Flex",
  //   transmission: "Automático",
  //   status: "Disponível",
  //   images: [
  //     "https://images.unsplash.com/photo-1618767747322-64e376fd4826?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "4",
  //   vehicleType: "Pickup",
  //   vehicleBrand: "Ford",
  //   model: "Ranger",
  //   year: 2022,
  //   price: 185000,
  //   color: "Preta",
  //   engineSize: "3.2L",
  //   mileage: 12000,
  //   fuelType: "Diesel",
  //   transmission: "Automático",
  //   status: "Reservado",
  //   images: [
  //     "https://images.unsplash.com/photo-1590043586864-d05a4ff3ec08?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "5",
  //   vehicleType: "SUV",
  //   vehicleBrand: "Jeep",
  //   model: "Renegade",
  //   year: 2021,
  //   price: 120000,
  //   color: "Preto",
  //   engineSize: "1.8L",
  //   mileage: 18000,
  //   fuelType: "Flex",
  //   transmission: "Automático",
  //   status: "Disponível",
  //   images: [
  //     "https://images.unsplash.com/photo-1635626398909-e33615b0c1d6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "6",
  //   vehicleType: "Sedan",
  //   vehicleBrand: "Hyundai",
  //   model: "Elantra",
  //   year: 2018,
  //   price: 89000,
  //   color: "Azul",
  //   engineSize: "2.0L",
  //   mileage: 60000,
  //   fuelType: "Gasolina",
  //   transmission: "Automático",
  //   status: "Vendido",
  //   images: [
  //     "https://images.unsplash.com/premium_photo-1737596468866-4c31416464c8?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   ],
  // },
  // {
  //   id: "7",
  //   vehicleType: "Hatch",
  //   vehicleBrand: "Chevrolet",
  //   model: "Onix",
  //   year: 2020,
  //   price: 78000,
  //   color: "Branco",
  //   engineSize: "1.0L",
  //   mileage: 40000,
  //   fuelType: "Flex",
  //   transmission: "Manual",
  //   status: "Vendido",
  //   images: [
  //     "https://imgs.search.brave.com/ah_seO0Rg3-r3MiW5I58ZR_y4gyJutWYQT6hXAZH_cc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy8y/LzJjL0NoZXZyb2xl/dF9Pbml4XzAwNi5q/cGc",
  //   ],
  // },
  // {
  //   id: "8",
  //   vehicleType: "SUV",
  //   vehicleBrand: "Nissan",
  //   model: "Kicks",
  //   year: 2022,
  //   price: 130000,
  //   color: "Preto",
  //   engineSize: "1.6L",
  //   mileage: 10000,
  //   fuelType: "Flex",
  //   transmission: "CVT",
  //   status: "Disponível",
  //   images: [
  //     "https://imgs.search.brave.com/v29mTZpQXjQuL3UmrBtjhDSFexQRk9PjBMLUdqZfX2M/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcy/LmljYXJyb3MuY29t/L2RiaW1nL2ltZ2Fk/aWNpb25hbGFudW5j/aW8vMS80MDAxNTI3/MzBfMS5qcGc",
  //   ],
  // },
  // {
  //   id: "9",
  //   vehicleType: "Crossover",
  //   vehicleBrand: "Peugeot",
  //   model: "2008",
  //   year: 2021,
  //   price: 98000,
  //   color: "Cinza",
  //   engineSize: "1.6L",
  //   mileage: 22000,
  //   fuelType: "Flex",
  //   transmission: "Automático",
  //   status: "Reservado",
  //   images: [
  //     "https://imgs.search.brave.com/xx2_6gYJY9Tn0IXCG6Y44rVKHs2PJ2ZbuUl0Lihx6ik/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YXV0b3BhcG8uY29t/LmJyL2JveC91cGxv/YWRzLzIwMjQvMDgv/MTIwOTE1NTAvcGV1/Z2VvdC0yMDA4LWd0/LTIwMjUtY2luemEt/ZnJlbnRlLWxhdGVy/YWwtdHJhc2VpcmEt/aW50ZXJpb3ItcGFp/bmVsMS03MzJ4NDg4/LmpwZw",
  //   ],
  // },
  // {
  //   id: "10",
  //   vehicleType: "Sedan",
  //   vehicleBrand: "Fiat",
  //   model: "Cronos",
  //   year: 2020,
  //   price: 85000,
  //   color: "Vermelho",
  //   engineSize: "1.3L",
  //   mileage: 30000,
  //   fuelType: "Flex",
  //   transmission: "Manual",
  //   status: "Reservado",
  //   images: [
  //     "https://imgs.search.brave.com/rkBtRDB32APoheFoB8my73_UJs2tS4i8rBtd7jDnmxA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/b2x4LmNvbS5ici90/aHVtYnM1MDB4MzYw/Lzk0Lzk0NDUzMTEy/ODIyMDI4MS5qcGc",
  //   ],
  // },
  // {
  //   id: "m1",
  //   vehicleType: "Street",
  //   vehicleBrand: "Honda",
  //   model: "CB 500F",
  //   year: 2021,
  //   price: 36000,
  //   color: "Vermelha",
  //   engineSize: "500cc",
  //   mileage: 8000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,honda"],
  // },
  // {
  //   id: "m2",
  //   vehicleType: "Naked",
  //   vehicleBrand: "Yamaha",
  //   model: "MT-03",
  //   year: 2022,
  //   price: 28000,
  //   color: "Preta",
  //   engineSize: "321cc",
  //   mileage: 4500,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Vendido",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,yamaha"],
  // },
  // {
  //   id: "m3",
  //   vehicleType: "Crossover",
  //   vehicleBrand: "BMW",
  //   model: "G 310 R",
  //   year: 2020,
  //   price: 29000,
  //   color: "Branca",
  //   engineSize: "313cc",
  //   mileage: 6000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Reservado",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,bmw"],
  // },
  // {
  //   id: "m4",
  //   vehicleType: "Naked",
  //   vehicleBrand: "Dafra",
  //   model: "Next 300",
  //   year: 2019,
  //   price: 17000,
  //   color: "Prata",
  //   engineSize: "278cc",
  //   mileage: 12000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,dafra"],
  // },
  // {
  //   id: "m5",
  //   vehicleType: "Esportiva",
  //   vehicleBrand: "Kawasaki",
  //   model: "Ninja 400",
  //   year: 2023,
  //   price: 35000,
  //   color: "Verde",
  //   engineSize: "399cc",
  //   mileage: 3000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Vendido",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,kawasaki"],
  // },
  // {
  //   id: "m6",
  //   vehicleType: "Custom",
  //   vehicleBrand: "Harley-Davidson",
  //   model: "Iron 883",
  //   year: 2018,
  //   price: 48000,
  //   color: "Preta",
  //   engineSize: "883cc",
  //   mileage: 9000,
  //   fuelType: "Gasolina",
  //   status: "Reservado",
  //   transmission: "Manual",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,harley"],
  // },
  // {
  //   id: "m7",
  //   vehicleType: "Crossover",
  //   vehicleBrand: "Triumph",
  //   model: "Street Twin",
  //   year: 2020,
  //   price: 42000,
  //   color: "Cinza",
  //   engineSize: "900cc",
  //   mileage: 7000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Reservado",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,triumph"],
  // },
  // {
  //   id: "m8",
  //   vehicleType: "Naked",
  //   vehicleBrand: "Suzuki",
  //   model: "GSX-S750",
  //   year: 2021,
  //   price: 39000,
  //   color: "Azul",
  //   engineSize: "749cc",
  //   mileage: 6500,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,suzuki"],
  // },
  // {
  //   id: "m9",
  //   vehicleType: "Custom",
  //   vehicleBrand: "Royal Enfield",
  //   model: "Meteor 350",
  //   year: 2022,
  //   price: 23000,
  //   color: "Amarela",
  //   engineSize: "349cc",
  //   mileage: 5000,
  //   fuelType: "Gasolina",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,enfield"],
  // },
  // {
  //   id: "m10",
  //   vehicleType: "Street",
  //   vehicleBrand: "Honda",
  //   model: "CG 160",
  //   year: 2021,
  //   price: 16000,
  //   color: "Preta",
  //   engineSize: "162cc",
  //   mileage: 9000,
  //   fuelType: "Flex",
  //   transmission: "Manual",
  //   status: "Disponível",
  //   images: ["https://images.unsplash.com/160x120/?motorcycle,cg160"],
  // },
];
