export const carBrandOptions = [
  "Aston Martin",
  "Audi",
  "BMW",
  "BYD",
  "CAOA Chery",
  "Chevrolet",
  "Citroën",
  "Effa",
  "Ferrari",
  "Fever",
  "Fiat",
  "Ford",
  "Foton",
  "GWM",
  "Honda",
  "Hyundai",
  "Iveco",
  "JAC",
  "Jaecoo",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Maserati",
  "McLaren",
  "Mercedes-AMG",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Neta",
  "Nissan",
  "Omoda",
  "Peugeot",
  "Porsche",
  "RAM",
  "Renault",
  "Riddara",
  "Rolls-Royce",
  "Seres",
  "Subaru",
  "Suzuki",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Zeekr",
];

export const motorcycleBrandOptions = [
  "Amazon",
  "Avelloz",
  "Bajaj",
  "BMW",
  "BRP",
  "Bull",
  "CFMoto",
  "Dafra",
  "Ducati",
  "Fever",
  "Haojue",
  "Harley-Davidson",
  "Honda",
  "Husqvarna",
  "Kawasaki",
  "KTM",
  "Kymco",
  "Leva",
  "LL Motors",
  "Motocar",
  "Motorino",
  "Mottu",
  "Niu",
  "Origem",
  "Piaggio",
  "Royal Enfield",
  "Shineray",
  "Sousa",
  "Suzuki",
  "Traxx",
  "Triumph",
  "Vespa",
  "Vmoto",
  "Voltz",
  "Watts",
  "Yamaha",
  "Zontes",
];

export const categoryOptions = ["Carro", "Moto"];

export const transmissionTypeOptions = [
  "Manual",
  "Automático",
  "Semi-Automático",
  "CVT (Transmissão Variável Contínua)",
  "Automatizada (Manual Automatizada)",
  "DCT (Dupla Embreagem)",
];

export const fuelTypeOptions = [
  "Gasolina",
  "Álcool", // cuidado: no enum está com erro de digitação, o correto seria "alcohol"
  "Flex",
  "Diesel",
  "Elétrico",
  "Híbrido", // também aqui: o correto seria "hybrid"
];

export const statusOptions = ["Disponível", "Vendido", "Reservado"];

export const carTypeOptions = [
  "Hatch",
  "Sedã",
  "SUV",
  "Crossover",
  "Picape",
  "Perua",
  "Conversível",
  "Coupé",
  "Minivan",
  "Van",
  "Utilitário",
];

export const motorcycleTypeOptions = [
  "Street",
  "Esportiva",
  "Touring",
  "Scooter",
  "Trail",
  "BigTrail",
  "Custom",
  "Off-road",
  "Naked",
];

export const bookingStatusOptions = [
  "Pendente",
  "Confirmado",
  "Cancelado",
  "Concluído",
  "Não Compareceu",
];

export const dayOfWeekOptions = [
  "Segunda-feira",
  "Terça-feira",
  "Quarta-feira",
  "Quinta-feira",
  "Sexta-feira",
  "Sábado",
  "Domingo",
];
